-- =============================================================================
-- Azure SQL schema for the Sunday School Library App
-- =============================================================================
-- Run this script once against your Azure SQL Database to create the schema.
-- All tables use NVARCHAR for Unicode text so that international characters
-- in book titles and author names are stored correctly.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    user_id     NVARCHAR(128)  NOT NULL,   -- Azure AD object ID or app-generated UUID
    name        NVARCHAR(256)  NOT NULL,
    email       NVARCHAR(320)  NOT NULL,
    password_hash NVARCHAR(256) NOT NULL,  -- bcrypt hash; never store plaintext
    role        NVARCHAR(32)   NOT NULL    -- 'librarian' | 'instructor' | 'general_user'
        CONSTRAINT chk_users_role CHECK (role IN ('librarian', 'instructor', 'general_user')),
    created_at  DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ---------------------------------------------------------------------------
-- Books
-- ---------------------------------------------------------------------------
CREATE TABLE books (
    isbn            NVARCHAR(20)   NOT NULL,  -- ISBN-10 or ISBN-13
    title           NVARCHAR(512)  NOT NULL,
    authors         NVARCHAR(MAX)  NOT NULL,  -- JSON array, e.g. ["Author A","Author B"]
    edition         NVARCHAR(64)   NULL,
    synopsis        NVARCHAR(MAX)  NULL,
    tags            NVARCHAR(MAX)  NULL,      -- JSON array, e.g. ["bible","children"]
    total_copies    INT            NOT NULL DEFAULT 0
        CONSTRAINT chk_books_total_copies CHECK (total_copies >= 0),
    available_copies INT           NOT NULL DEFAULT 0
        CONSTRAINT chk_books_available_copies CHECK (available_copies >= 0),
    created_at      DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at      DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT pk_books PRIMARY KEY (isbn),
    CONSTRAINT chk_books_available_lte_total
        CHECK (available_copies <= total_copies)
);

-- ---------------------------------------------------------------------------
-- Checkouts
-- ---------------------------------------------------------------------------
CREATE TABLE checkouts (
    checkout_id  NVARCHAR(36)   NOT NULL,  -- UUID generated by the API
    book_id      NVARCHAR(20)   NOT NULL,
    user_id      NVARCHAR(128)  NOT NULL,
    quantity     INT            NOT NULL DEFAULT 1
        CONSTRAINT chk_checkouts_quantity CHECK (quantity > 0),
    date_out     DATETIME2      NOT NULL DEFAULT SYSUTCDATETIME(),
    date_in      DATETIME2      NULL,      -- NULL while the book is still checked out
    notes        NVARCHAR(1024) NULL,
    CONSTRAINT pk_checkouts PRIMARY KEY (checkout_id),
    CONSTRAINT fk_checkouts_book   FOREIGN KEY (book_id)  REFERENCES books (isbn),
    CONSTRAINT fk_checkouts_user   FOREIGN KEY (user_id)  REFERENCES users (user_id),
    CONSTRAINT chk_checkouts_date_in CHECK (date_in IS NULL OR date_in >= date_out)
);

CREATE INDEX idx_checkouts_user_id ON checkouts (user_id);
CREATE INDEX idx_checkouts_book_id ON checkouts (book_id);
CREATE INDEX idx_checkouts_active  ON checkouts (book_id) WHERE date_in IS NULL;
